fastlane_version "1.96.0"

platform :ios do
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")

    increment_build_number(
      xcodeproj: './ios/digisquare.xcodeproj'
    )

    gym(
      scheme: "digisquare",
      project: './ios/digisquare.xcodeproj'
    )

    commit_version_bump(
      message: "Deployed new build #{lane_context[SharedValues::BUILD_NUMBER]}",
      xcodeproj: './ios/digisquare.xcodeproj'
    )

    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "digisquare") # Build your app - more options available
    deliver(force: true)
    # frameit
  end
end

platform :android do
  desc "Deploy a new version to the Google Play Store"
  lane :alpha do
    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "android/"
    )
    supply(
      track: "alpha",
      apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    )
  end
end
